//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkeeBall.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SkeeBallNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SkeeBallNames"]));
            }
            set {
                this["SkeeBallNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SkeeBallScores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SkeeBallScores"]));
            }
            set {
                this["SkeeBallScores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Game310Names {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Game310Names"]));
            }
            set {
                this["Game310Names"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Game310Scores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Game310Scores"]));
            }
            set {
                this["Game310Scores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ClassicNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ClassicNames"]));
            }
            set {
                this["ClassicNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ClassicScores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ClassicScores"]));
            }
            set {
                this["ClassicScores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FlashBallNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FlashBallNames"]));
            }
            set {
                this["FlashBallNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FlashBallScores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FlashBallScores"]));
            }
            set {
                this["FlashBallScores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Nick</string>
  <string>Kat</string>
  <string>Ben</string>
  <string>Erin</string>
  <string>Kush</string>
  <string>Neetu</string>
  <string>Wayne</string>
  <string>Becky</string>
  <string>Nat</string>
  <string>Jamie</string>
  <string>Dom</string>
  <string>Laurie</string>
  <string>Skank</string>
  <string>Steve</string>
  <string>Create New</string>
  <string>Melanie</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PlayerList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PlayerList"]));
            }
            set {
                this["PlayerList"] = value;
            }
        }
    }
}
