//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkeeBall.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ModernNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ModernNames"]));
            }
            set {
                this["ModernNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ModernScores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ModernScores"]));
            }
            set {
                this["ModernScores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ThreeTenNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ThreeTenNames"]));
            }
            set {
                this["ThreeTenNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>99</string>
  <string>99</string>
  <string>99</string>
  <string>99</string>
  <string>99</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ThreeTenScores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ThreeTenScores"]));
            }
            set {
                this["ThreeTenScores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ClassicNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ClassicNames"]));
            }
            set {
                this["ClassicNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ClassicScores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ClassicScores"]));
            }
            set {
                this["ClassicScores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MultiNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MultiNames"]));
            }
            set {
                this["MultiNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MultiScores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MultiScores"]));
            }
            set {
                this["MultiScores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>NICK</string>
  <string>KAT</string>
  <string>BEN</string>
  <string>KUSH</string>
  <string>WAYNE</string>
  <string>BECKY</string>
  <string>NAT</string>
  <string>JAMIE</string>
  <string>DOM</string>
  <string>LAURIE</string>
  <string>SKANK</string>
  <string>STEVE</string>
  <string>MELANIE</string>
  <string>CREATE NEW</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PlayerList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PlayerList"]));
            }
            set {
                this["PlayerList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CricketNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CricketNames"]));
            }
            set {
                this["CricketNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>99</string>
  <string>99</string>
  <string>99</string>
  <string>99</string>
  <string>99</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CricketScores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CricketScores"]));
            }
            set {
                this["CricketScores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
  <string>SkeeBall</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FiveTenNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FiveTenNames"]));
            }
            set {
                this["FiveTenNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>99</string>
  <string>99</string>
  <string>99</string>
  <string>99</string>
  <string>99</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FiveTenScores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FiveTenScores"]));
            }
            set {
                this["FiveTenScores"] = value;
            }
        }
    }
}
